// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	v1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
	mock "github.com/stretchr/testify/mock"
)

// AuditLogging is an autogenerated mock type for the AuditLogging type
type AuditLogging struct {
	mock.Mock
}

// Enable provides a mock function with given fields: ctx, shoot, mandatory
func (_m *AuditLogging) Enable(ctx context.Context, shoot *v1beta1.Shoot, mandatory bool) (bool, error) {
	ret := _m.Called(ctx, shoot, mandatory)

	if len(ret) == 0 {
		panic("no return value specified for Enable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Shoot, bool) (bool, error)); ok {
		return rf(ctx, shoot, mandatory)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Shoot, bool) bool); ok {
		r0 = rf(ctx, shoot, mandatory)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta1.Shoot, bool) error); ok {
		r1 = rf(ctx, shoot, mandatory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuditLogging creates a new instance of AuditLogging. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogging(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogging {
	mock := &AuditLogging{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
