// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	v1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
	auditlogging "github.com/kyma-project/infrastructure-manager/internal/auditlogging"
	mock "github.com/stretchr/testify/mock"
	types "k8s.io/apimachinery/pkg/types"
)

// AuditLogConfigurator is an autogenerated mock type for the AuditLogConfigurator type
type AuditLogConfigurator struct {
	mock.Mock
}

// CanEnableAuditLogsForShoot provides a mock function with given fields: seedName
func (_m *AuditLogConfigurator) CanEnableAuditLogsForShoot(seedName string) bool {
	ret := _m.Called(seedName)

	if len(ret) == 0 {
		panic("no return value specified for CanEnableAuditLogsForShoot")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(seedName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetConfigFromFile provides a mock function with given fields:
func (_m *AuditLogConfigurator) GetConfigFromFile() (map[string]map[string]auditlogging.AuditLogData, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigFromFile")
	}

	var r0 map[string]map[string]auditlogging.AuditLogData
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]map[string]auditlogging.AuditLogData, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]map[string]auditlogging.AuditLogData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]auditlogging.AuditLogData)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolicyConfigMapName provides a mock function with given fields:
func (_m *AuditLogConfigurator) GetPolicyConfigMapName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPolicyConfigMapName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSeedObj provides a mock function with given fields: ctx, seedKey
func (_m *AuditLogConfigurator) GetSeedObj(ctx context.Context, seedKey types.NamespacedName) (v1beta1.Seed, error) {
	ret := _m.Called(ctx, seedKey)

	if len(ret) == 0 {
		panic("no return value specified for GetSeedObj")
	}

	var r0 v1beta1.Seed
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.NamespacedName) (v1beta1.Seed, error)); ok {
		return rf(ctx, seedKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.NamespacedName) v1beta1.Seed); ok {
		r0 = rf(ctx, seedKey)
	} else {
		r0 = ret.Get(0).(v1beta1.Seed)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.NamespacedName) error); ok {
		r1 = rf(ctx, seedKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateShoot provides a mock function with given fields: ctx, shoot
func (_m *AuditLogConfigurator) UpdateShoot(ctx context.Context, shoot *v1beta1.Shoot) error {
	ret := _m.Called(ctx, shoot)

	if len(ret) == 0 {
		panic("no return value specified for UpdateShoot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Shoot) error); ok {
		r0 = rf(ctx, shoot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditLogConfigurator creates a new instance of AuditLogConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogConfigurator {
	mock := &AuditLogConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
