package comparator

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "shoot-comparator",
	Short: "shoot-comparator - tool for comparing whether shoots generated by KIM,and Provisioner are the same.",
	Run: func(cmd *cobra.Command, args []string) {
	},
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to execute  shoot comparator: '%s'", err)
		os.Exit(1)
	}
}
